### ISSUE TITLE
Forgot nodelet_plugins.xml

### ISSUE THREAD

**Issue by zlacelle** [astuff/flir_boson_usb#5]
The repo packages (at least on Kinetic, probably others) don't correctly install nodelet_plugins.xml. As such, the nodelet loader can't load the nodelet. 

To fix, add in CMakeLists.txt
```
install(FILES nodelet_plugins.xml DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
```

**Comment by JWhitleyWork** [comment]
@zlacelle - This has been done in `master` but wasn't in the current release. I've created a new release for `kinetic` and `melodic` which will be pushed to the official repos on the next package sync. Keep an eye on https://discourse.ros.org/tags/release for the next sync (probably 2-3 weeks). Thanks!
